services:
  app:
    build: .
    restart: always
    env_file:
      - .env
    environment:
      - TZ=America/Sao_Paulo
    ports:
      - "3000:3000"
    networks:
      - jim-network

networks:
  jim-network:
    external: true

volumes:
  rabbitmq_data: